### PR TITLE
Kevin

### PR DESCRIPTION
**Pull request by ngynkvn**
Responsive mobile
image

### CODE REVIEW

**Comment by ngynkvn** [comment]
image

**Review by rieckn — APPROVED** [review]
Looks good to me. How can I test on mobile myself because I think my tag pr will probably look weird on mobile?

**Comment by ngynkvn** [comment]
> 
> 
> Looks good to me. How can I test on mobile myself because I think my tag pr will probably look weird on mobile?

You can click this icon in dev tools:
image

**Comment by sussam** [comment]
Looks good. Ideally I'd want the navbar to be all in one line but I can experiment with that. We can definitely decrease the size of sort discussion to match the search bar.

**Review by sussam — APPROVED** [review]

**Pull request merged**
